### ISSUE TITLE
Invalid site gets details of last successful scan

### ISSUE THREAD

**Issue by fishouttah20** [0xprime/CertificateScanner#1]
When using a -targets file, any domains which are invalid (no DNS) or which don't respond on the ports specified, still show up in the results but display the CommonName and certificate details of the last successfully connected to host.

**Comment by 0xprime** [comment]
Thanks. I will look into it when I get back.

**Comment by 0xprime** [comment]
Hi @fishouttah20, 

I seem to be unable to replicate the issue. Can you provide me with an example?

**Comment by fishouttah20** [comment]
Sorry, I seem to be unable to replicate it as well. It was on an internal corporate network and the only thing I can think is that something internal (proxy) responded making them show as live, but can't work out why the results didn't match the intercepting proxy certificate.

**Comment by 0xprime** [comment]
I added an extra round of parameter cleanup, which should prevent this in the future.
